// SPDX-FileCopyrightText: Copyright 2026 NVIDIA CORPORATION & AFFILIATES
// SPDX-License-Identifier: Apache-2.0

//! Emits fixed signing-key bytes at compile time for the `yaml-sigil-test-keys` crate.
//!
//! This crate is intended only as a **dev-dependency** so key material is not built for
//! normal `cargo build` / `cargo check` of `yaml-sigil-verification` or `yaml-sigil-signing`.

use rand::SeedableRng;
use std::env;
use std::fs;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=YAML_SIGIL_TEST_KEY_SEED");

    let seed = parse_seed_or_build_unique();
    let mut rng = rand::rngs::StdRng::seed_from_u64(seed);

    let ed0 = ed25519_dalek::SigningKey::generate(&mut rng);
    let ed1 = ed25519_dalek::SigningKey::generate(&mut rng);
    let p0 = p256::ecdsa::SigningKey::random(&mut rng);
    let p1 = p256::ecdsa::SigningKey::random(&mut rng);

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let path = Path::new(&out_dir).join("buildtime_test_keys.rs");
    let mut src = String::new();
    src.push_str("// @generated by build.rs — do not edit.\n");
    src.push_str("// Workspace-only test key material (yaml-sigil-test-keys).\n\n");
    src.push_str(&format!(
        "/// `YAML_SIGIL_TEST_KEY_SEED` or a build-unique 64-bit seed used for `StdRng`.\npub const BUILD_TIME_SEED: u64 = {seed};\n\n"
    ));
    src.push_str(&format_array(
        "ED25519_SIGNING_KEY_BYTES_0",
        &ed0.to_bytes(),
    ));
    src.push_str(&format_array(
        "ED25519_SIGNING_KEY_BYTES_1",
        &ed1.to_bytes(),
    ));
    src.push_str(&format_array(
        "P256_SIGNING_KEY_BYTES_0",
        p0.to_bytes().as_ref(),
    ));
    src.push_str(&format_array(
        "P256_SIGNING_KEY_BYTES_1",
        p1.to_bytes().as_ref(),
    ));

    fs::write(&path, src).expect("write buildtime_test_keys.rs");
}

fn parse_seed_or_build_unique() -> u64 {
    if let Ok(s) = env::var("YAML_SIGIL_TEST_KEY_SEED")
        && let Ok(v) = s.parse::<u64>()
    {
        return v;
    }

    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos())
        .unwrap_or(0x9E37_79B1_85EB_CA87_u128);
    let pid = u128::from(std::process::id());
    let mixed = nanos ^ (pid << 48) ^ (pid << 17);
    (mixed as u64) ^ ((mixed >> 64) as u64)
}

fn format_array(name: &str, bytes: &[u8]) -> String {
    let elems = bytes
        .iter()
        .map(|b| format!("{b}"))
        .collect::<Vec<_>>()
        .join(", ");
    format!("pub const {name}: [u8; {}] = [{elems}];\n\n", bytes.len())
}
